In [1]:
import numpy as np

In [2]:
a=np.random.rand(5)

In [3]:
a

array([0.91936736, 0.31324959, 0.28703259, 0.06487481, 0.99952482])

In [4]:
a=np.exp(a)

In [5]:
a

array([2.50770342, 1.3678629 , 1.33246764, 1.06702543, 2.71699047])

In [6]:
a=a/np.sum(a)

In [7]:
a

array([0.27888006, 0.15211914, 0.14818286, 0.1186632 , 0.30215474])

In [8]:
np.sum(a)

1.0

In [22]:
A=np.random.randn(100,5)

In [23]:
A

array([[-1.79350109e+00, -1.16380380e+00,  8.03471958e-01,
         8.53199081e-01, -9.80720777e-01],
       [ 1.49338375e+00,  1.04420210e+00,  4.63602195e-01,
         8.54737970e-01,  1.86453466e-01],
       [ 2.28844481e+00, -9.31967190e-01,  4.15217487e-01,
        -2.77171637e+00, -1.54902591e+00],
       [ 1.50746759e+00,  3.52878274e-01, -6.75961371e-01,
        -2.93415473e-01,  5.45202297e-02],
       [ 1.81882464e+00,  1.23221411e+00,  4.47083312e-01,
         5.10860104e-01, -1.10359392e+00],
       [ 2.16914097e+00, -9.55437552e-01,  1.18513417e+00,
        -2.93946364e-01, -1.57915923e-01],
       [-1.61046533e+00,  1.28333519e-01, -2.16595054e-01,
        -1.36345427e+00, -1.12904554e+00],
       [-6.09852586e-03, -2.31913079e-02, -5.60257746e-02,
         4.43086161e-01, -3.63914546e-01],
       [-4.98062665e-01, -1.96409040e+00,  6.32200097e-01,
         2.09928362e-01, -1.64476788e-01],
       [ 8.55222275e-01,  1.51513909e+00, -8.46652100e-01,
         9.10894740e-01

In [24]:
expA=np.exp(A)

In [25]:
expA

array([[ 0.16637665,  0.31229601,  2.23328134,  2.34714356,  0.37504068],
       [ 4.45213497,  2.84113068,  1.58979042,  2.35075833,  1.20496855],
       [ 9.85959218,  0.39377831,  1.51470013,  0.06255455,  0.21245482],
       [ 4.51528175,  1.4231579 ,  0.50866717,  0.74571225,  1.05603384],
       [ 6.16460855,  3.4288129 ,  1.56374457,  1.66672413,  0.33167692],
       [ 8.75076363,  0.38464381,  3.27112568,  0.74531647,  0.85392157],
       [ 0.19979462,  1.13693213,  0.80525599,  0.25577573,  0.32334173],
       [ 0.99392003,  0.97707554,  0.94551477,  1.55750653,  0.69495058],
       [ 0.60770685,  0.14028343,  1.88174605,  1.23358969,  0.84833745],
       [ 2.35189709,  4.55005394,  0.42884827,  2.48654635,  3.58310476],
       [ 0.59115419,  0.38663707,  1.09008664,  1.15004496,  0.50897019],
       [ 2.02376923, 11.73046753,  1.00612826,  0.6282454 ,  0.18489096],
       [ 2.17709934,  1.04358293,  2.75586427,  2.05908556,  1.51719301],
       [ 0.49885429,  0.91007356,  2.2

In [26]:
answer=expA/expA.sum(axis=1,keepdims=True)

In [27]:
answer

array([[0.03061693, 0.05746928, 0.41097249, 0.43192563, 0.06901567],
       [0.35792368, 0.22840906, 0.12780916, 0.1889862 , 0.0968719 ],
       [0.81869357, 0.03269748, 0.12577348, 0.00519423, 0.01764124],
       [0.54738299, 0.17252798, 0.0616652 , 0.09040193, 0.1280219 ],
       [0.46859314, 0.26063589, 0.11886562, 0.12669345, 0.02521191],
       [0.62479699, 0.02746324, 0.23355556, 0.05321495, 0.06096927],
       [0.07342421, 0.41782075, 0.2959303 , 0.09399717, 0.11882757],
       [0.19228599, 0.18902722, 0.1829214 , 0.3013187 , 0.13444669],
       [0.12897926, 0.02977365, 0.3993804 , 0.26181617, 0.18005052],
       [0.17550881, 0.33954485, 0.03200253, 0.18555692, 0.26738689],
       [0.1586185 , 0.10374247, 0.29249206, 0.30858008, 0.13656689],
       [0.12994953, 0.75323251, 0.06460514, 0.04034066, 0.01187215],
       [0.2279011 , 0.10924338, 0.28848683, 0.21554729, 0.1588214 ],
       [0.07865086, 0.14348492, 0.35890873, 0.31336167, 0.10559383],
       [0.03268078, 0.24838212, 0.

(100,)