In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

1.12.0


# Tensorflow basic operation

In [5]:
hello=tf.constant("hello")
world=tf.constant("world")

In [6]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [7]:
world


<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [9]:
with tf.Session() as sess:
    result=sess.run(hello+world)

In [13]:
result

b'helloworld'

In [14]:
a=tf.constant(10)

In [17]:
b=tf.constant(20)

In [18]:
type(a)

tensorflow.python.framework.ops.Tensor

In [20]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [22]:
with tf.Session() as sess:
    result=sess.run(a+b)

In [23]:
result

30

In [24]:
const=tf.constant(40)

In [25]:
fill_mat=tf.fill((4,4),10)

In [26]:
zeroes=tf.zeros((4,4))

In [27]:
ones=tf.ones((4,4))

In [33]:
random_num_normal=tf.random_normal((4,4))

In [34]:
random_num_uniform=tf.random_uniform((4,4),minval=0,maxval=10)

In [35]:
my_ops=[const,fill_mat,ones,zeroes,random_num_normal,random_num_uniform]

In [36]:
sess=tf.InteractiveSession()

In [38]:
sess.run(my_ops)

In [41]:
for op in my_ops:
    print(sess.run(op))
    print("\n")

40


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[-0.77574134 -0.26416045  0.35956943 -0.57616675]
 [ 0.11443187  0.63657165  0.84916204  1.105969  ]
 [ 0.41237566  0.8946579  -1.3424971   1.2926208 ]
 [-0.58152956  0.51317227  0.9190534  -0.42666304]]


[[7.690859   9.751321   3.6978543  0.28696656]
 [9.363289   5.8517637  1.718216   3.0124092 ]
 [3.567276   3.6825025  9.121409   8.468269  ]
 [2.2689831  4.129978   4.818898   8.487721  ]]


